### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pkoenders** [BretCameron/sanity-plugin-order-documents#5] opened 2020-10-27 09:48 UTC
Hi Bret, thanks for this plugin, it is great to use in Sanity and all is ordering fine there.

When I am trying to sort with GraphiQL, all my 'order' nodes return a value of 0.

allMyNames(sort: {fields: order, order: DESC}) {

Anything I am missing?

Thanks
P

**Comment by BretCameron** [comment] 2020-10-28 14:19
Hi Peter, it looks like your syntax doesn't quite match [the sorting syntax described here](https://www.sanity.io/docs/graphql).

The following GraphQL syntax is working for me:

```graphql
query {
  allMovie(sort: [ { order: ASC }, { _updatedAt: DESC } ]) {
    title
    order
    #etc
  }
}
```

This should be equivalent to the GROQ:

```groq
*[_type == "movie"] | order(order asc, _updatedAt desc)
```

<img width="835" alt="Screenshot 2020-10-28 at 14 15 54" src="https://user-images.githubusercontent.com/44526664/97448056-1e241700-1928-11eb-94da-f6f1a988e009.png">

I hope this fixes your problem! 

I've added a GraphQL example to the README, to help anyone else who encounters this issue.

**Comment by BretCameron** [comment] 2020-10-31 14:21
I'm going to close this issue, in the hope that the problem is solved!

As an additional note, sorting is not part of GraphQL by default. So, you have to it yourself or use an API which has sorting built-in. 

Most people using Sanity will be using the Sanity GraphQL API, where the sort syntax looks like this:

```graphql
query {
  allMyNames(sort: [ { order: ASC } ]) {
    order
  }
}
```

But be aware that if you have a custom GraphQL setup, the syntax may be different!

**Closed as completed by BretCameron** 2020-10-31 14:21 UTC
